[project]
name = "web-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GreedyFoolish", email = "1158984036@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "openai==2.44.0",
    "oss2>=2.19.1",
    "pyjwt>=2.15.1",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
