[project]
name = "web-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GreedyFoolish", email = "1158984036@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic==1.18.4",
    "asyncpg==0.31.0",
    "web-utils",
    "fastapi[standard]==0.136.3",
    "psycopg2-binary==2.9.12",
    "pydantic-settings==2.14.1",
    "sqlalchemy[asyncio]==2.0.50",
    "loguru>=0.7.3",
]

# [project.scripts]
# web-service = "web_service.main:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
web-utils = { workspace = true }

# [tool.uv.build-backend] 
# module-root = "src"
# module-name = "web_service"